eureka:
  client:
    healthcheck:
      enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）
  instance:
    lease-expiration-duration-in-seconds: 10 # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 5 # 续约更新时间间隔（默认30秒）
security:
  oauth2:
    resource:
      loadBalanced: true #这个参数在OAuth2LoadBalancerClientAutoConfiguration可以找到，设置这个才可以使用eureka的服务名，配合loadBalancerInterceptor bean。
      user-info-uri: http://cdp-authserver/oauth/principal
      prefer-token-info: false
spring:
  zipkin:
    baseUrl: http://cdp-sleuthserver/
    sender:
      type: rabbit
    locator:
      discovery:
        enabled: true
    discovery-client-enabled: true
  #禁用sleuth，改用rabbitmq
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: ${spring.rabbitmq.host}:${spring.rabbitmq.port}
      username: ${spring.rabbitmq.username}
      password: ${spring.rabbitmq.password}
      queue: zipkin
  query:
    allowed-origins: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false #解决zipkin异常：Prometheus requires that all meters with the same name have the same set of tag keys
