spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.137.155:3306/cdp_platform?useUnicode=true&characterEncoding=utf-8
    username: cdp
    password: local
    druid:
      driver-class-name: com.mysql.jdbc.Driver
#    platform: mysql
#    continue-on-error: true
  redis:
    host: 192.168.137.155
    port: 6379
    password: local
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
management:
  security:
    enabled: false
security:
  user:
    name: cdp
    password: local
  oauth2:
    resource:
      filter-order: 3
      loadBalanced: true #这个参数在OAuth2LoadBalancerClientAutoConfiguration可以找到，设置这个才可以使用eureka的服务名，配合loadBalancerInterceptor bean。
      user-info-uri: http://cdp-authserver/oauth/principal
      prefer-token-info: false
      service-id: cdp-platformserver
#logging:
#  level:
#    org:
#      springframework:
#        web: info
#  config: classpath:logback.xml.bak
cdp:
  swagger:
    enabled: true
    title: ${spring.application.name}
    description: ${info.description}
    version: ${info.version}
    base-package: com.github.fosin.cdp.platform
    authorization:
      name: Oauth2.0 Authorization
      keyName: Authorization
    contact:
      name: fosin
      email: 28860823@qq.com
#  global-operation-parameters:
#  - name: Authorization
#    description: Oauth2.0令牌信息,格式例如：Bearer 58cb49cd-be59-4706-bbc5-9c41fc3cbef4
#    modelRef: string
#    parameterType: header
#    required: true
  oauth2:
    disablecsrf: true
    disableHttpBasic: true
    blackWhiteList:
    - path: /**/v2/api-docs