spring:
  boot:
    admin:
      turbine:
        location: cdp-adminserver
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,turbine.stream
turbine:
  cluster-name-expression: new String('default')
  app-config: cdp-zuulgateway
cdp:
  oauth2:
    disablecsrf: true
    disableHttpBasic: true
    cors:
      allowedOrigins: '*'
      allowedMethods: '*'
      allowedHeaders: '*'
      allowCredentials: true
    blackWhiteList:
      - path: /**/*.html
      - path: /**/*.css
      - path: /**/*.js
      - path: /**/img/**
      - path: /third-party/**
      - path: /**/api/**
      - path: /**/login/**
      - path: /**/logout/**
      - path: /**/applications/**
      - path: /**/instances/**
      - method: OPTIONS
security:
  oauth2:
    client:
      client-id: appServer
      client-secret: appServer
      access-token-uri: http://localhost:1400/oauth/token
      grant-type: client_credentials
