security:
  oauth2:
    resource:
      filter-order: 3
      loadBalanced: true #这个参数在OAuth2LoadBalancerClientAutoConfiguration可以找到，设置这个才可以使用eureka的服务名，配合loadBalancerInterceptor bean。
      user-info-uri: http://cdp-authserver/oauth/principal
      prefer-token-info: false
      service-id: cdp-sleuthserver
management:
  security:
    enabled: false
spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://192.168.137.155:3306/cdp_zipkin
    username: '{cipher}AQBmphzkCLxk9OmJtZ4IUmbueDwos79U5y0URmC1zlH3fO+V7GtqBxKAxnSarOjPewUK55njl+NBrdOtBkElTrqwmcCT0Np4V9IOot/B85JARWbB3QJhJIHnwSOEYKWW0VCutaRfxphBfOa2dvS52kwi+qWI8KF/rghLeM8nHqKA6sOFeWwr0gyRK7gcMILyrjMEnX3UqZkw0C6+yoHN2ssnCcEpYIhZRo8yzSqh/dBWfraUV867lMKUMMVxNZBLuKvW0HBWRTGjpZwP6AoMAJtHtyUueRk+8WZ3YytL/Y95Ou2ckbJF7LD273eS06YdKsktqIicexrRV4/HAKF96JE71CiHY6U43sgylp5ziEFCbMkqPn7ZMkvQdRw+SQBJfpM='
    password: '{cipher}AQBKDi1e2O8RxX1JkwCpYZ8gdF8uFahNH3oUvFrEM8UXfmJGWthztlBOxvDFNB4Cqu6FZKibXkZZEWStiLvATSl6+EiWMEhQqBv1Kt8u65Qquzxt5Ab/IdTP1EGUA2i0KN0Mi+TArbRjoXwxvh5DjqQ4Td22QhgnhRCn8USpmNF9vcma0if/DIPyjweOYaayF5ynJO3gTibPLDjOj194DbeXnmR1nVlO/hcfjM5a65Hr+rRoisgSUbOCcsAuxluEhDT35+rjEPumxaRo58DOckq0XkJhoyQ69g/Do3NBEx0ewEcEVg2t/DJyPp9BbSRGYV67HUqup39c//RuhP2AHTN94qZgrxEBtBsGu+E1E/xtBjNjqSeQPdeJb200dTF99rQ='
    continueOnError: true
    initialize: true
zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: ${spring.rabbitmq.host}:${spring.rabbitmq.port}
      username: ${spring.rabbitmq.username}
      password: ${spring.rabbitmq.password}
      queue: zipkin
  query:
    allowed-origins: '*'
cdp:
  oauth2:
    disablecsrf: true
    disableHttpBasic: true
    cors:
      allowedOrigins: '*'
      allowedMethods: '*'
      allowedHeaders: '*'
      allowCredentials: true
    blackWhiteList:
    - path: /**/*.html
    - path: /**/*.css
    - path: /**/*.js
    - path: /zipkin/**
    - method: OPTIONS