version: "3"
services:
  nacos-server1:
    image: nacos/nacos-server:1.1.4
    container_name: nacos-server1
    hostname: nacos-server1
    environment:
      - TZ=Asia/Shanghai
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql-master
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=local
      - MYSQL_SLAVE_SERVICE_HOST=mysql-slave
      - MYSQL_SLAVE_SERVICE_PORT=3306
#      - MYSQL_SERVICE_HOST=nacos-mysql
#      - MYSQL_SERVICE_PORT=3308
#      - MYSQL_SERVICE_DB_NAME=nacos
#      - MYSQL_SERVICE_USER=nacos
#      - MYSQL_SERVICE_PASSWORD=local
#      - MYSQL_DATABASE_NUM=1
      - JVM_XMS=512M
      - JVM_XMX=512M
      - JVM_XMN=256M
    volumes:
      -  /root/deploy/nacos/logs/:/home/nacos/logs
#      -  /root/deploy/nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - mysql-master
      - mysql-slave
    networks:
      - anan-bridge
  nacos-mysql:
    container_name: nacos-mysql
    hostname: nacos-mysql
    image: nacos/nacos-mysql:5.7
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=local
    volumes:
      - /root/deploy/mysql/nacos:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - anan-bridge
  mysql-master:
    container_name: mysql-master
    hostname: mysql-master
    image: fosin/mysql-master:5.7
#    build:
#      context: deploy/mysql/master
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_REPLICATION_USER=anan_ru
      - MYSQL_REPLICATION_PASSWORD=local
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=local
      - MYSQL_DATABASE2=anan_platform
      - MYSQL_USER2=anan
      - MYSQL_PASSWORD2=local
    volumes:
      - /root/deploy/nfs/mysql-master0:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - anan-bridge
  mysql-slave:
    container_name: mysql-slave
    hostname: mysql-slave
    image: fosin/mysql-slave:5.7
#    build:
#      context: deploy/mysql/slave
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_REPLICATION_USER=anan_ru
      - MYSQL_REPLICATION_PASSWORD=local
      - MYSQL_SERVICE_HOST=mysql-master
    volumes:
      - /root/deploy/nfs/mysql-slave0:/var/lib/mysql
    ports:
      - "3305:3306"
    depends_on:
      - mysql-master
    networks:
      - anan-bridge
  filebeat:
    image: elastic/filebeat:6.8.6
    container_name: filebeat
    hostname: filebeat
    restart: on-failure
    user: root
    volumes:
      - /root/deploy/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/deploy/filebeat/logs/filebeat:/logs:ro
#    environment:
#      - output.elasticsearch.hosts=["elasticsearch:9200"]
#      - output.logstash.enabled=false
#      - setup.kibana.host=kibana:5601
    # disable strict permission checks
    command: ["--strict.perms=false"]
#    ports:
#      - 5601:5601
    networks:
      - anan-bridge
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:6.8.6
    container_name: kibana
    hostname: kibana
    restart: on-failure
    environment:
      - I18N_LOCALE=zh-CN
#      -SERVER_NAME=kibana.example.org
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - anan-bridge
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.8.6
    container_name: elasticsearch
    hostname: elasticsearch
    restart: on-failure
    environment:
#      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /root/deploy/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - anan-bridge

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    hostname: zipkin
    restart: on-failure
    environment:
      - STORAGE_TYPE=elasticsearch
      # Point the zipkin at the storage backend
      - ES_HOSTS=elasticsearch
#      - RABBIT_CONNECTION_TIMEOUT=60000
#      - RABBIT_VIRTUAL_HOST=/
#      - RABBIT_USE_SSL=false
#      - RABBIT_QUEUE=zipkin
      # Uncomment to see requests to and from elasticsearch
      # - ES_HTTP_LOGGING=BODY
      - RABBIT_ADDRESSES=rabbitmq:5672
      - RABBIT_USER=anan
      - RABBIT_PASSWORD=local
    networks:
      - anan-bridge
    depends_on:
      - elasticsearch
      - rabbitmq
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=anan
      - RABBITMQ_DEFAULT_PASS=local
      - RABBITMQ_DEFAULT_VHOST=/
      - TZ=Asia/Shanghai
    #    volumes: TODO 启动后报错cookie file /var/lib/rabbitmq/.erlang.cookie must be accessible by owner only
    #      - /root/deploy/rabbitmq:/var/lib/rabbitmq
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - anan-bridge

  anan-vue:
    container_name: anan-vue
    image: fosin/anan-vue:3.0.1
    hostname: anan-vue
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/deploy/nginx/conf:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      - anan-bridge

  redis:
    image: redis:4.0
    container_name: redis
    hostname: redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/deploy/redis:/data
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass local
    networks:
      - anan-bridge

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USER=admin
      - ADMIN_PASS=local
      - REDIS_1_AUTH=local
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    ports:
      - 6380:80
    networks:
      - anan-bridge

  mongodb:
    image: mongo:3.4
    container_name: mongodb
    hostname: mongodb
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=anan
      - MONGO_INITDB_ROOT_PASSWORD=local
    volumes:
      - /root/deploy/mongodb/db:/data/db
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - anan-bridge

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /root/deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    #      - /root/deploy/prometheus/data:/prometheus TODO 不能挂载外部目录，报错
    restart: on-failure
    privileged: true
    depends_on:
      - cadvisor
      - node-exporter
    ports:
      - 9090:9090
    networks:
      - anan-bridge

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
      - NODE_ID={{.Node.ID}}
    cap_add:
      - SYS_TIME
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    networks:
      - anan-bridge

  grafana:
    image: grafana/grafana:6.1.3
    container_name: grafana
    hostname: grafana
    volumes:
      - /root/deploy/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SECURITY_ADMIN_PASSWORD=local
      - GF_USERS_ALLOW_SIGN_UP='false'
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - anan-bridge

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    hostname: cadvisor
    environment:
      - TZ=Asia/Shanghai
    restart: on-failure
    privileged: true
    volumes:
      - /dev/disk/:/dev/disk:ro
      - /cgroup:/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - anan-bridge

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    hostname: alertmanager
    restart: on-failure
    ports:
      - 9093:9093
    networks:
      - anan-bridge
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-devops-alerts}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
#    volumes:
#      - /root/deploy/alertmanager/data:/alertmanager
  #    - /root/deploy/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  unsee:
    container_name: unsee
    hostname: unsee
    image: cloudflare/unsee:v0.8.0
    restart: on-failure
    networks:
      - anan-bridge
    environment:
      - TZ=Asia/Shanghai
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"

  anan-zuulgateway:
    image: fosin/anan-zuulgateway:2.1.0-SNAPSHOT
    entrypoint: "sh /anan/wait-for.sh anan-platformserver:51500 -t 3600 -- /anan/entrypoint.sh"
    container_name: anan-zuulgateway
    hostname: anan-zuulgateway
    restart: on-failure
    environment:
      - JAVA_OPTS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M
    ports:
      - 9000:9000
#    volumes:
      #- /root/deploy/logs/anan:/logs
    networks:
      - anan-bridge
    depends_on:
      - rabbitmq
      - nacos-server1

  anan-authserver:
    image: fosin/anan-authserver:2.1.0-SNAPSHOT
    entrypoint: "sh /anan/wait-for.sh nacos-server1:8848 -t 3600 -- /anan/entrypoint.sh"
    container_name: anan-authserver
    hostname: anan-authserver
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:ErrorFile=/logs/hs_err_pid%p.log -Xlog:gc:/logs/gc%t.log
    ports:
      - 51400:51400
#    volumes:
      #- /root/deploy/logs/anan:/logs
    networks:
      - anan-bridge
    depends_on:
      - rabbitmq
      - redis
      - mysql-master
      - nacos-server1

  anan-platformserver:
    image: fosin/anan-platformserver:2.1.0-SNAPSHOT
    entrypoint: "sh /anan/wait-for.sh anan-authserver:51400 -t 3600 -- /anan/entrypoint.sh"
    container_name: anan-platformserver
    hostname: anan-platformserver
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M
#    volumes:
      #- /root/deploy/logs/anan:/logs
    ports:
      - 51500:51500
    networks:
      - anan-bridge
    depends_on:
      - rabbitmq
      - redis
      - mysql-master
      - nacos-server1

  anan-adminserver:
    image: fosin/anan-adminserver:2.1.0-SNAPSHOT
#    entrypoint: "sh /anan/wait-for.sh anan-zuulgateway:9000 -t 3600 -- /anan/entrypoint.sh"
    container_name: anan-adminserver
    hostname: anan-adminserver
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M
#    volumes:
      #- /root/deploy/logs/anan:/logs
    ports:
      - 51700:51700
    networks:
      - anan-bridge
    depends_on:
      - rabbitmq
      - redis
      - nacos-server1

  anan-eurekaserver:
    image: fosin/anan-eurekaserver:2.1.0-SNAPSHOT
    container_name: anan-eurekaserver
    hostname: anan-eurekaserver
    restart: on-failure
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M
    networks:
      - anan-bridge
#    volumes:
      #- /root/deploy/logs/anan:/logs
    ports:
      - 51000:51000

  anan-configserver:
    image: fosin/anan-configserver:2.1.0-SNAPSHOT
    entrypoint: "sh /anan/wait-for.sh anan-eurekaserver:51000 -t 3600 -- /anan/entrypoint.sh"
    container_name: anan-configserver
    hostname: anan-configserver
    restart: on-failure
    ports:
      - 51100:51100
    environment:
      - JAVA_TOOL_OPTIONS=-Xmx512M -Xms512M -Xmn256M -XX:MaxMetaspaceSize=128M -XX:MetaspaceSize=128M
      - spring.cloud.config.server.native.search-locations=file:/anan-config
#    volumes:
      #- /root/deploy/logs/anan:/logs
      - /root/deploy/anan-config:/anan-config
    networks:
      - anan-bridge
    depends_on:
      - anan-eurekaserver
      - rabbitmq

  postgresql:
    image: postgres
    container_name: postgresql
    hostname: postgresql
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    networks:
      - anan-bridge

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    hostname: sonarqube
    restart: on-failure
    ports:
      - 9001:9000
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
    networks:
      - anan-bridge
    depends_on:
      - postgresql
networks:
  anan-bridge:
    external: true
