version: "3"
services:
  cdp-db:
    container_name: cdp-db
    hostname: cdp-db
    image: mysql:5.7
    #    build:
    #      context: ./
    #      dockerfile: ./sql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${defaultPassword}
    volumes:
      - ${dataPath}mysql/data:/var/lib/mysql
      - ${dataPath}mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ${dataPath}mysql/logs:/var/log/mysql
    restart: on-failure
    ports:
      - 3306:3306

  cdp-rabbitmq:
    container_name: cdp-rabbitmq
    hostname: cdp-rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: cdp
      RABBITMQ_DEFAULT_PASS: ${defaultPassword}
      RABBITMQ_DEFAULT_VHOST: /
    restart: on-failure
    ports:
      - 15672:15672
      - 5672:5672

  cdp-nginx:
    container_name: cdp-nginx
    image: nginx
    hostname: cdp-nginx
    volumes:
      - ${dataPath}nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${dataPath}nginx/html:/usr/share/nginx/html
    ports:
      - 80:80

  cdp-redis:
    container_name: cdp-redis
    hostname: cdp-redis
    image: redis:4.0
    volumes:
      - ${dataPath}redis:/data
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass ${defaultPassword}

  cdp-eurekaserver:
    image: fosin/cdp-eurekaserver:1.0.0-SNAPSHOT-local
    container_name: cdp-eurekaserver
    hostname: cdp-eurekaserver
    restart: on-failure
    ports:
      - 1000:1000

  cdp-configserver:
    image: fosin/cdp-configserver:1.0.0-SNAPSHOT-local
    container_name: cdp-configserver
    hostname: cdp-configserver
    restart: on-failures
    ports:
      - 1100:1100
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-eurekaserver
      - cdp-rabbitmq

  cdp-zuulgateway:
    image: fosin/cdp-zuulgateway:1.0.0-SNAPSHOT-local
    container_name: cdp-zuulgateway
    hostname: cdp-zuulgateway
    restart: on-failure
    ports:
      - 9000:9000
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-configserver
      - cdp-db

  cdp-authserver:
    image: fosin/cdp-authserver:1.0.0-SNAPSHOT-local
    container_name: cdp-authserver
    hostname: cdp-authserver
    restart: on-failure
    ports:
      - 1400:1400
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-configserver
      - cdp-redis
      - cdp-db

  cdp-platformserver:
    image: fosin/cdp-platformserver:1.0.0-SNAPSHOT-local
    container_name: cdp-platformserver
    hostname: cdp-platformserver
    restart: on-failure
    ports:
      - 1500:1500
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-configserver
      - cdp-redis
      - cdp-db

  cdp-adminserver:
    image: fosin/cdp-adminserver:1.0.0-SNAPSHOT-local
    container_name: cdp-adminserver
    hostname: cdp-adminserver
    restart: on-failure
    ports:
      - 1700:1700
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-configserver

  cdp-sleuthserver:
    image: fosin/cdp-sleuthserver:1.0.0-SNAPSHOT-local
    container_name: cdp-sleuthserver
    hostname: cdp-sleuthserver
    restart: on-failure
    ports:
      - 1800:1800
    links:
      - cdp-eurekaserver
      - cdp-rabbitmq
    depends_on:
      - cdp-configserver
      - cdp-db
