apiVersion: apps/v1
kind: Deployment
metadate:
  name: anan-platform-mysql-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anan-platform-mysql
  template:
    metadata:
      labels:
        app: anan-platform-mysql
    spec:
      containers:
      - name: anan-platform-mysql
        image: registry.cn-hangzhou.aliyuncs.com/fosin/anan-platform-mysql:2.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        nodeSelector:
          kubernetes.io/hostname=local1
        ports:
        - containerPort: 3306
        env:
        - name: TZ
          value: Asia/Shanghai
        - name: MYSQL_ROOT_PASSWORD
          value: local
        volumeMounts:
        - name: "platform_mysql_data"
          mountPath: /var/lib/mysql
          readOnly: false    
        - name: "mysqlconf"     
          mountPath: /etc/mysql/conf.d/mysqld.cnf
          readOnly: true
        - name: "platform_mysql_log"     
          mountPath: /var/log/mysql
          readOnly: false
        resources:
          limits:
            memory: 256M
          requests:
            memory: 128M  
        volumes:
        - name: platform_mysql_data
          hostPath:
            path: ./mysql/anan_platform/data
        - name: mysqlconf
          configMap:
            name: mysql_configMap 
        - name: platform_mysql_log
          hostPath:
            path: ./mysql/anan_platform/logs 
---
apiVersion: v1
kind: Service
metadata:
  name: anan-platform-mysql-service
  labels:
    app: anan-platform-mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: anan-platform-mysql
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql_configMap
data:
  mysqld.cnf: |
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    #log-error      = /var/log/mysql/error.log
    # By default we only accept connections from localhost
    #bind-address   = 127.0.0.1
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    #SHOW GLOBAL VARIABLES LIKE 'log_timestamps';默认为UTC，修改为SYSTEM
    log_timestamps=SYSTEM
    #不区分大小写
    lower_case_table_names=1
    #skip-grant-tables
    #skip-name-resolve
    #服务器端和客户端字符集
    character_set_server=utf8mb4

    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4
