apiVersion: v1
kind: ConfigMap
metadata:
  name: base-cm
data:
  mysql.master.db.name: "nacos"
  mysql.master.port: "3306"
  mysql.slave.port: "3306"
  mysql.master.user: "nacos"
  mysql.master.password: "nacos"
  mysql.root.password: "local"
  mysql.replication.user: "nacos_ru"
  mysql.replication.password: "nacos_ru"
  tz: "Asia/Shanghai"
  user: "anan"
  password: "local"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  serviceName: mysql-master
  replicas: 1
  selector:
    matchLabels:
      name: mysql-master
  template:
    metadata:
      labels:
        name: mysql-master
    spec:
      nodeSelector:
        kubernetes.io/hostname: local1
      containers:
        - name: master
          image: nacos/nacos-mysql-master:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-master-data
              mountPath: /var/lib/mysql
            - name: mysqlconf
              mountPath: /etc/mysql/conf.d/mysqld.cnf
              readOnly: true
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: tz
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.root.password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.db.name
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.user
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.password
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.replication.user
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.replication.password
          resources:
            limits:
              memory: 256M
            requests:
              memory: 128M
      volumes:
        - name: mysql-master-data
          hostPath:
            path: /root/deploy/nacos/mysql-master
        - name: mysqlconf
          configMap:
            name: mysql-configmap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  serviceName: mysql-slave
  replicas: 1
  selector:
    matchLabels:
      name: mysql-slave
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      nodeSelector:
        kubernetes.io/hostname: local2
      initContainers:
        - name: init-slave
          image: busybox
          command: ['sh', '-c', 'until nslookup mysql-master; do echo waiting for mysql-master; sleep 2; done;']
      containers:
        - name: slave
          image: nacos/nacos-mysql-slave:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-slave-data
              mountPath: /var/lib/mysql
            - name: mysqlconf
              mountPath: /etc/mysql/conf.d/mysqld.cnf
              readOnly: true
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: tz
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.root.password
            - name: MYSQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.replication.user
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.replication.password
          resources:
            limits:
              memory: 256M
            requests:
              memory: 128M
      volumes:
        - name: mysql-slave-data
          hostPath:
            path: /root/deploy/nacos/mysql-slave
        - name: mysqlconf
          configMap:
            name: mysql-configmap
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 2
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: nacos-headless-log
          hostPath:
            path: /root/deploy/nacos/logs
      initContainers:
        - name: init-mysql-slave
          image: busybox
          command: ['sh', '-c', 'until nslookup mysql-slave; do echo waiting for mysql-slave; sleep 2; done;']
      containers:
        - name: k8snacos
          image: nacos/nacos-server:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2G"
              cpu: "500m"
            limits:
              memory: "2G"
          ports:
            - containerPort: 8848
              name: client
          volumeMounts:
            - name: nacos-headless-log
              mountPath: /home/nacos/logs
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: tz
            - name: NACOS_REPLICAS
              value: "2"
            - name: MYSQL_MASTER_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.db.name
            - name: MYSQL_MASTER_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.port
            - name: MYSQL_SLAVE_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.slave.port
            - name: MYSQL_MASTER_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.user
            - name: MYSQL_MASTER_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: mysql.master.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        appCluster: redis-cluster
    spec:
      terminationGracePeriodSeconds: 20
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis
                topologyKey: kubernetes.io/hostname
      containers:
        - name: redis
          image: redis:4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: tz
          command:
            - "redis-server /etc/redis/redis.conf"
          resources:
            requests:
              memory: "32M"
            limits:
              memory: "64M"
          ports:
            - name: redis
              containerPort: 6379
            - name: cluster
              containerPort: 16379
          volumeMounts:
            - name: "redis-data"
              mountPath: "/data"
            - name: "redis-conf"
              mountPath: "/etc/redis"
      volumes:
        - name: "redis-data"
          hostPath:
            path: "/root/deploy/redis"
        - name: "redis-conf"
          configMap:
            name: "redis-configmap"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      volumes:
        - name: "rabbitmq-data"
          hostPath:
            path: "/root/deploy/rabbitmq"
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: tz
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: user
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: base-cm
                  key: password
            - name: RABBITMQ_ERLANG_COOKIE
              value: SWQOKODSQALRPCLNMEQG
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_SERVICE_NAME
              value: "rabbitmq"
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_NODENAME
              value: "rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME)"
            - name: RABBITMQ_NODE_TYPE
              value: disc
            - name: AUTOCLUSTER_TYPE
              value: "k8s"
            - name: AUTOCLUSTER_DELAY
              value: "10"
            - name: AUTOCLUSTER_CLEANUP
              value: "true"
            - name: CLEANUP_WARN_ONLY
              value: "false"
            - name: K8S_ADDRESS_TYPE
              value: "hostname"
            - name: K8S_HOSTNAME_SUFFIX
              value: ".$(K8S_SERVICE_NAME)"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    name: mysql-master
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  type: NodePort
  selector:
    name: mysql-master
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30002
  type: NodePort
  selector:
    name: mysql-slave
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 30000
  selector:
    app: nacos
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
    - name: redis-cluster-port
      port: 16379
      targetPort: 16379
  selector:
    app: redis
    appCluster: redis-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
    - port: 15672
      name: rabbit-management
      nodePort: 30003
    - port: 5672
      targetPort: 5672
      name: amqp
  selector:
    app: rabbitmq
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  mysqld.cnf: |
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    #log-error      = /var/log/mysql/error.log
    # By default we only accept connections from localhost
    #bind-address   = 127.0.0.1
    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
    #SHOW GLOBAL VARIABLES LIKE 'log_timestamps';默认为UTC，修改为SYSTEM
    log_timestamps=SYSTEM
    #不区分大小写
    lower_case_table_names=1
    #skip-grant-tables
    #skip-name-resolve
    #服务器端和客户端字符集
    character_set_server=utf8mb4

    [client]
    default-character-set = utf8mb4

    [mysql]
    default-character-set = utf8mb4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-configmap
data:
  redis.conf: |
    appendonly yes
    cluster-enabled yes
    cluster-config-file /var/lib/redis/nodes.conf
    cluster-node-timeout 5000
    port 6379
    requirepass local
