{{- if .Values.es }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-env
data:
  username: {{ include "anan.user" . | quote }}
  password: {{ .Values.es.password | default ( include "anan.password" .) | quote }}
  serviceHeadless: {{ include "anan.service.headless.name" . | quote }}
  port: {{ index (index .Values.service.ports 0) "targetPort" | quote }}
  portTransport: {{ index (index .Values.service.ports 1) "targetPort" | quote }}
  addresses: {{ include "anan.service.headless.name" . }}:{{ index (index .Values.service.ports 0) "targetPort" }}
{{- end }}
