{{- if .Values.configmap }}
{{- if .Values.configmap.confs }}
{{ include "anan.configmap.conf" . }}
{{- end }}

{{- if .Values.configmap.envs }}
{{ include "anan.configmap.env" . }}
{{- end }}
{{- end }}

{{ if .Values.service }}
{{- if .Values.statefulset }}
---
{{ include "anan.service.headless" . }}
{{ if eq .Values.service.type "NodePort" }}
---
{{ include "anan.service" . }}
{{ end }}
{{- else }}
---
{{ include "anan.service" . }}
{{ end }}
{{ end }}

{{- if .Values.deployment }}
---
{{ include "anan.deployment" . }}
{{- end }}

{{- if .Values.statefulset }}
---
{{ include "anan.statefulset" . }}
{{- end }}

{{- if .Values.daemonset }}
---
{{ include "anan.daemonset" . }}
{{- end }}

{{- if .Values.clusterRole }}
---
{{ include "anan.cluster.role" . }}
---
{{ include "anan.cluster.rolebinding" . }}
{{- end }}

{{- if .Values.role }}
---
{{ include "anan.role" . }}
---
{{ include "anan.rolebinding" . }}
{{- end }}

{{- if or .Values.clusterRole .Values.role }}
---
{{ include "anan.serviceaccount" . }}
{{- end }}

{{- if .Values.persistence }}
{{- if .Values.persistence.nfs }}
---
{{ include "anan.persistentvolume.nfs" . }}
---
{{ include "anan.persistentvolumeclaim.nfs" . }}
{{- end }}
{{- end }}
