{{- if .Values.nacos }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-env
data:
  JVM_XMS: {{ .Values.jvm.xms }}
  JVM_XMX: {{ .Values.jvm.xmx }}
  JVM_XMN: {{ .Values.jvm.xmn }}
  NACOS_REPLICAS: {{ .Values.replicaCount | quote }}
  NACOS_SERVERS:
  {{- $replicaCount := int .Values.replicaCount }}
  {{- $headlessName := (include "anan.service.headless.name" .) }}
  {{- range $i, $e := until $replicaCount -}}
  {{- indent 1 "" }}{{ $.Release.Name }}-{{ $i }}.{{ $headlessName }}.{{ $.Release.Namespace }}.svc.cluster.local:{{ index (index $.Values.service.ports 0) "targetPort" }}
  {{- end }}
  NACOS_SERVER_PORT: {{ index (index .Values.service.ports 0) "targetPort" | quote }}
  PREFER_HOST_MODE: "hostname"
{{- end }}
