{{- if .Values.redis }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
data:
  redis.conf: |
    appendonly yes
    cluster-enabled yes
    cluster-config-file /var/lib/redis/nodes.conf
    cluster-node-timeout 10000
    dir /var/lib/redis
    appendfilename appendonly.aof
    dbfilename dump.rdb
    port 6379
    {{- if .Values.redis.password }}
    masterauth {{ .Values.redis.password }}
    requirepass {{ .Values.redis.password }}
    {{- else }}
    masterauth {{ include "anan.password" . }}
    requirepass {{ include "anan.password" . }}
    {{- end }}
    maxmemory {{ .Values.resources.limits.memory }}B
    maxmemory-policy allkeys-lru
    databases 1
{{- end }}
