{{- if .Values.redis }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-env
data:
  password: {{ .Values.redis.password | default ( include "anan.password" .) | quote }}
  serviceHeadless: {{ include "anan.service.headless.name" . | quote }}
  port: {{ index (index .Values.service.ports 0) "targetPort" | quote }}
  portCluster: {{ index (index .Values.service.ports 1) "targetPort" | quote }}
{{- end }}
