image: appbaseio/dejavu
imagePullPolicy: IfNotPresent
replicaCount: 1
resources:
  limits:
    memory: 256Mi
  requests:
    memory: 128Mi
livenessProbe:
  initialDelaySeconds: 180
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 1358
readinessProbe:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 1358
env: {}
volumeMounts: {}
volumes: {}
initContainers:
  - name: wait-es
    image: busybox
    command: ['sh', '-c', 'until nc es-headless 9200; do echo waiting for es; sleep 2; done;']
service:
  type: NodePort
  ports:
    - port: 1358
      targetPort: 1358
      nodePort: 1358
      name: elastichd
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
persistence: {}
configmap:
  envs: {}
  confs: {}
