es:
  password:
statefulset:
  updateStrategy:
    type: RollingUpdate
image: elasticsearch:6.8.6
imagePullPolicy: IfNotPresent
replicaCount: 1
#resources:
#  limits:
#    memory: 1Gi
#  requests:
#    cpu: 1m
#    memory: 1Gi
livenessProbe:
  initialDelaySeconds: 80
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 9200
readinessProbe:
  initialDelaySeconds: 50
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 9200
env:
  - name: ES_JAVA_OPTS
    value: "-Xms1g -Xmx1g"
  - name: bootstrap.memory_lock
    value: "false"
  - name: "NAMESPACE"
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
envFrom: {}
args: {}
command: {}
volumeMounts:
  - name: es
    mountPath: /usr/share/elasticsearch/data
service:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 9200
      name: db
    - port: 9300
      targetPort: 9300
      name: transport
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
initContainers:
    - image: alpine:3.6
      command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
      name: elasticsearch-init
      securityContext:
        privileged: true
persistence:
  enabled: true
  #  storageClassName: "es-storage-class"
  size: 10G
  accessMode: ReadWriteOnce
  nfs:
    - server: 192.168.137.8
clusterRole:
  lables: {}
  rules:
    - apiGroups:
        - ""
      resources:
        - "services"
        - "namespaces"
        - "endpoints"
      verbs:
        - "get"
configmap:
  envs: {}
  confs:
    elasticsearch.yml: |
      #
      # Copyright 2015-2019 The OpenZipkin Authors
      #
      # Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
      # in compliance with the License. You may obtain a copy of the License at
      #
      # http://www.apache.org/licenses/LICENSE-2.0
      #
      # Unless required by applicable law or agreed to in writing, software distributed under the License
      # is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
      # or implied. See the License for the specific language governing permissions and limitations under
      # the License.
      #
      network.host: 0.0.0.0
      discovery.zen.minimum_master_nodes: 1
      xpack.ml.enabled: false

      # 使用Chrome 插件方式（不能使用）
      #http.port: 9200
      #http.cors.allow-origin: 'chrome-extension://jopjeaiilkcibeohjdmejhoifenbnmlh'
      #http.cors.enabled: true
      #http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      #http.cors.allow-credentials: true

      # 使用Docker容器
      http.port: 9200
      http.cors.allow-origin: '*'
      http.cors.enabled: true
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: true
