statefulset:
  updateStrategy:
    type: RollingUpdate
image: fosin/mysql-slave:2.1.0
imagePullPolicy: IfNotPresent
replicaCount: 1
mysql:
  slave:
    port: 3306
resources:
  limits:
    memory: 384Mi
  requests:
    cpu: 1m
    memory: 256Mi
persistence:
  enabled: true
  #  storageClassName: "anan-nfs"
  size: 1G
  accessMode: ReadWriteOnce
  nfs:
    - server: 192.168.137.8
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: name
                operator: NotIn
                values:
                  - mysql-master
          topologyKey: kubernetes.io/hostname
service:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 3306
      name: mysql
env:
  - name: TZ
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: anan.tz
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.root.password
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.nacos.dbname
  - name: MYSQL_USER
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.nacos.user
  - name: MYSQL_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.nacos.password
  - name: MYSQL_REPLICATION_USER
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.replication.user
  - name: MYSQL_REPLICATION_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.replication.password
  - name: MYSQL_MASTER_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: mysql-master-env
        key: mysql.master.service.host
volumeMounts:
  - name: mysql-slave
    mountPath: /var/lib/mysql
configmap:
  envs: {}
  confs: {}
