statefulset:
  updateStrategy:
    type: RollingUpdate
mysql:
  nacos:
    password: "local"
    user: "nacos"
    dbname: "nacos"
  platform:
    password: "local"
    user: "anan"
    dbname: "anan_platform"
  replication:
    user: "anan_ru"
    password: "local"
  leader:
    port: 3306
  rootPassword: "local"
image: fosin/mysql-leader:2.1.0
imagePullPolicy: IfNotPresent
replicaCount: 1
createCm: true
resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 1m
    memory: 256Mi
persistence:
  enabled: true
#  storageClassName: "anan-nfs"
  size: 1G
  accessMode: ReadWriteOnce
  nfs:
    - server: 192.168.137.8
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: name
                operator: NotIn
                values:
                  - mysql-follower
          topologyKey: kubernetes.io/hostname
service:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 3306
      name: mysql
env:
  - name: TZ
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: anan.tz
  - name: MYSQL_ROOT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.root.password
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.nacos.dbname
  - name: MYSQL_USER
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.nacos.user
  - name: MYSQL_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.nacos.password
  - name: MYSQL_REPLICATION_USER
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.replication.user
  - name: MYSQL_REPLICATION_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.replication.password
  - name: MYSQL_MASTER_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: mysql.leader.service.host
volumeMounts:
  - name: mysql-leader
    mountPath: /var/lib/mysql
configmap:
  envs: {}
  confs: {}
