redis:
  password:
  createRedisAdmin: true
statefulset:
  updateStrategy:
    type: RollingUpdate
image: redis:5.0
imagePullPolicy: IfNotPresent
replicaCount: 6
resources:
  limits:
    memory: 256M
  requests:
    cpu: 1m
    memory: 128M
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 6379
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  tcpSocket:
    port: 6379
env: {}
command:
  - "redis-server"
args:
  - "/etc/redis/redis.conf"
  - "--protected-mode"
  - "no"
volumeMounts:
  - name: redis-conf
    mountPath: "/etc/redis"
  - name: redis
    mountPath: "/var/lib/redis"
volumes:
  - name: redis-conf
    configMap:
      name: redis-conf
      items:
        - key: "redis.conf"
          path: "redis.conf"
persistence:
  enabled: true
  size: 1G
  accessMode: ReadWriteOnce
  nfs:
    - server: 192.168.137.8
    - server: 192.168.137.8
    - server: 192.168.137.8
    - server: 192.168.137.8
    - server: 192.168.137.8
    - server: 192.168.137.8
service:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 6379
      name: redis
    - port: 16379
      targetPort: 16379
      nodePort: 16379
      name: cluster
terminationGracePeriodSeconds: 30
