image: openzipkin/zipkin:2
imagePullPolicy: IfNotPresent
replicaCount: 1
deployment:
  strategy:
    rollingUpdate:  ##由于replicas为2,则整个升级,pod个数在2-3个之间
      maxSurge: 1      #滚动升级时会先启动1个pod
      maxUnavailable: 1 #滚动升级时允许的最大Unavailable的pod个数
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
service:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
      nodePort: 9411
      name: one
persistence: {}
resources:
  limits:
    memory: 512Mi
  requests:
    memory: 512Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 5
  tcpSocket:
    port: 9411
  httpGet: null
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 5
  tcpSocket:
    port: 9411
  httpGet: null
env:
  - name: TZ
    valueFrom:
      configMapKeyRef:
        name: mysql-leader-env
        key: anan.tz
  - name: JAVA_TOOL_OPTIONS
    valueFrom:
      configMapKeyRef:
        name: anan-env
        key: JAVA_TOOL_OPTIONS
#    value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:MaxRAMPercentage=70 -XX:InitialRAMPercentage=50"
    #            - name: STORAGE_TYPE
    #              value: "mem"
    #使用es报错， Fielddata is disabled on text fields by default. Set fielddata=true on [localEndpoint.serviceName] in order to load fielddata in memory by uninverting the inverted index.
  - name: STORAGE_TYPE
    value: "elasticsearch"
  - name: ES_HOSTS
    valueFrom:
      configMapKeyRef:
        name: es-env
        key: addresses
  - name: ES_USERNAME
    valueFrom:
      configMapKeyRef:
        name: es-env
        key: username
  - name: ES_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: es-env
        key: password
  # Uncomment to see requests to and from elasticsearch
  #            - name: ES_HTTP_LOGGING
  #              value: "BODY"
  - name: RABBIT_ADDRESSES
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: addresses
  - name: RABBIT_USER
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: username
  - name: RABBIT_PASSWORD
    valueFrom:
      configMapKeyRef:
        name: rabbitmq-env
        key: password
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
initContainers:
  - name: wait-rabbitmq
    image: busybox
    command: ['sh', '-c', 'until nc rabbitmq-headless 5672; do echo waiting for rabbitmq; sleep 2; done;']
configmap:
  envs: {}
  confs: {}
