deployment:
  lables: {}
  strategy: {}
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
daemonset:
  lables: {}
  updateStrategy: {}
  minReadySeconds: 60  #滚动升级时60s后认为该pod就绪
statefulset:
  lables: {}
  updateStrategy:
    type: RollingUpdate
image: busybox
imagePullPolicy: IfNotPresent
replicaCount: 1
revisionHistoryLimit: 10
resources: {}
livenessProbe: {}
readinessProbe: {}
env: []
envFrom: []
args: []
command: []
volumeMounts: []
volumes: []
volumeClaimTemplates: []
lifecycle: {}
affinity: {}
securityContext: {}
initContainers: []
nodeSelector: {}
tolerations: []
persistence:
  lables: {}
  size: 1G
  storageClassName:
  accessMode: ReadWriteOnce
  nfs:
    - server: 127.0.0.1
      path: ""
service:
  lables: {}
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      nodePort: 80
      protocol: TCP
      name: cluster
serviceAccountName:
terminationGracePeriodSeconds: 30 #优雅关闭pod的等待时间，默认30s
role:
  lables: {}
  rules: []
clusterRole:
  lables: {}
  rules: []
configmap:
  envs: {}
  confs: {}
