version: "3"
services:
  anan-platform-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/fosin/anan-platform-mysql:2.0.0-SNAPSHOT
    networks:
      - anan-overlay
    depends_on:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
    volumes:
      - ./mysql/anan_platform/data:/var/lib/mysql
      - ./mysql/anan_platform/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql/anan_platform/logs:/var/log/mysql
    ports:
      - 3306:3306
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
  nacos-mysql-master:
    image: nacos/nacos-mysql-master:latest
    networks:
      - anan-overlay
    depends_on:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_REPLICATION_USER=nacos_ru
      - MYSQL_REPLICATION_PASSWORD=nacos_ru
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - ./mysql/nacos-mysql-master/data:/var/lib/mysql
      - ./mysql/nacos-mysql-master/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql/nacos-mysql-master/logs:/var/log/mysql
    ports:
      - 3306:3306
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
  nacos-mysql-slave:
    image: nacos/nacos-mysql-slave:latest
    networks:
      - anan-overlay
    depends_on:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
      - MYSQL_REPLICATION_USER=nacos_ru
      - MYSQL_REPLICATION_PASSWORD=nacos_ru
      - MYSQL_MASTER_SERVICE_HOST=nacos-mysql-master
    volumes:
      - ./mysql/nacos-mysql-slave/data:/var/lib/mysql
      - ./mysql/nacos-mysql-slave/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql/nacos-mysql-slave/logs:/var/log/mysql
    ports:
      - 3305:3306
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role != manager]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
  nacos-server1:
    image: nacos/nacos-server:latest
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server1:8848 nacos-server2:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=nacos-mysql-master
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=nacos
      - MYSQL_SLAVE_SERVICE_HOST=nacos-mysql-slave
      - MYSQL_SLAVE_SERVICE_PORT=3305
    volumes:
      -  ./nacos/logs/nacos-server1/:/home/nacos/logs
      -  ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    depends_on:
      - nacos-mysql-master
      - nacos-mysql-slave
  nacos-server2:
    image: nacos/nacos-server:latest
    environment:
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-server1:8848 nacos-server2:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=nacos-mysql-master
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_USER=nacos
      - MYSQL_MASTER_SERVICE_PASSWORD=nacos
      - MYSQL_SLAVE_SERVICE_HOST=nacos-mysql-slave
      - MYSQL_SLAVE_SERVICE_PORT=3305
    volumes:
      -  ./nacos/logs/nacos-server2/:/home/nacos/logs
      -  ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    depends_on:
      - nacos-mysql-master
      - nacos-mysql-slave
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=anan
      - RABBITMQ_DEFAULT_PASS=local
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - anan-overlay
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 258M
        reservations:
          memory: 64M

  redis:
    image: redis:4.0
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M
    networks:
      - anan-overlay

networks:
  anan-overlay:
    external: true
