version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    environment:
      - TZ=Asia/Shanghai
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=24h'
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - cdp-overlay
    depends_on:
      - cdp-overlay
      - cadvisor
    ports:
      - 9090:9090
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # 每次更新1个副本
        delay: 5s # 每次更新间隔
        monitor: 10s # 单次更新多长时间后没有结束则判定更新失败
        max_failure_ratio: 0.1 # 更新时能容忍的最大失败率
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    networks:
      - cdp-overlay
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-devops-alerts}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
#      -./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  unsee:
    image: cloudflare/unsee:v0.8.0
    networks:
      - cdp-overlay
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  grafana:
    image: grafana/grafana:latest
    volumes:
      -./grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SECURITY_ADMIN_PASSWORD=local
      - GF_USERS_ALLOW_SIGN_UP='false'
    ports:
      - 3000:3000
    networks:
      - cdp-overlay
    depends_on:
      - cdp-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # 每次更新1个副本
        delay: 5s # 每次更新间隔
        monitor: 10s # 单次更新多长时间后没有结束则判定更新失败
        max_failure_ratio: 0.1 # 更新时能容忍的最大失败率
      placement:
        constraints: [node.role == manager]

  node-exporter:
    image: prom/node-exporter:latest
    environment:
      - NODE_ID={{.Node.ID}}
      - TZ=Asia/Shanghai
    ports:
      - 9100:9100
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    networks:
      - cdp-overlay
    depends_on:
      - cdp-overlay
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # 每次更新1个副本
        delay: 5s # 每次更新间隔
        monitor: 10s # 单次更新多长时间后没有结束则判定更新失败
        max_failure_ratio: 0.1 # 更新时能容忍的最大失败率
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: google/cadvisor:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - cdp-overlay
    depends_on:
      - cdp-overlay
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1 # 每次更新1个副本
        delay: 5s # 每次更新间隔
        monitor: 10s # 单次更新多长时间后没有结束则判定更新失败
        max_failure_ratio: 0.1 # 更新时能容忍的最大失败率
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  prometheus: {}
  alertmanager: {}

networks:
  cdp-overlay:
    external: true