version: "3"
services:
  anan-platform-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/fosin/anan-platform-mysql:2.0.0-SNAPSHOT
    networks:
      - anan-overlay
    depends_on:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=local
    volumes:
      - ./mysql/anan_platform/data:/var/lib/mysql
      - ./mysql/anan_platform/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./mysql/anan_platform/logs:/var/log/mysql
    ports:
      - 3306:3306
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=anan
      - RABBITMQ_DEFAULT_PASS=local
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - anan-overlay
    ports:
      - 15672:15672
      - 5672:5672
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 258M
        reservations:
          memory: 64M

  redis:
    image: redis:4.0
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis:/data
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --requirepass local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M
    networks:
      - anan-overlay

  nginx:
    image: nginx:1.15
    networks:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]

networks:
  anan-overlay:
    external: true
