version: "3"
services:
  anan-authserver:
    image: fosin/anan-authserver:2.1.0-SNAPSHOT
    entrypoint: "sh /bin/wait-for.sh nacos-server1:8848 -t 3600 -- java -jar /app.jar"
    networks:
      - anan-overlay
    volumes:
      - ../logs:/logs
    ports:
      - 51400:51400
    depends_on:
      - redis
      - anan-platform-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  anan-platformserver:
    image: fosin/anan-platformserver:2.1.0-SNAPSHOT
    entrypoint: "sh /bin/wait-for.sh anan-authserver:51400 -t 3600 -- java -jar /app.jar"
    networks:
      - anan-overlay
    volumes:
      - ../logs:/logs
    ports:
      - 51500:51500
    depends_on:
      - anan-configserver
      - redis
      - anan-platform-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  anan-zuulgateway:
    image: fosin/anan-zuulgateway:2.1.0-SNAPSHOT
    entrypoint: "sh /bin/wait-for.sh anan-platformserver:51500 -t 3600 -- java -jar /app.jar"
    volumes:
      - ../logs:/logs
    ports:
      - 9000:9000
    networks:
      - anan-overlay
    depends_on:
      - anan-configserver
      - anan-platform-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  anan-adminserver:
    image: fosin/anan-adminserver:2.1.0-SNAPSHOT
    entrypoint: "sh /bin/wait-for.sh anan-zuulgateway:9000 -t 3600 -- java -jar /app.jar"
    networks:
      - anan-overlay
    volumes:
      - ../logs:/logs
    ports:
      - 51700:51700
    depends_on:
      - anan-zuulgateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  nginx:
    image: nginx:1.15
    networks:
      - anan-overlay
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/html:/usr/share/nginx/html
    ports:
      - 80:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 999
      update_config:
        delay: 5s
      placement:
        constraints: [node.role == manager]

networks:
  anan-overlay:
    external: true
