name: anan-cloud Branches CI
on:
  push:
    branches:
      - '*'
    paths:
      - 'pom.xml'
      - 'anan-cloudadviced/pom.xml'
      - 'anan-cloudadviced/anan-platform/pom.xml'
      - 'anan-cloudadviced/anan-platform/anan-platformapi/**'
      - 'anan-cloudadviced/anan-platform/anan-platformpojo/**'
      - 'deploy/mysql/**'
      - 'deploy/openjdk/**'
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      #从11位截取GITHUB_REF变量中的分支号，例如:refs/heads/master，结果就是master
      - name: Set GITHUB_REF
        run: echo ::set-env name=MODULE_VERSION::$(echo ${GITHUB_REF:11})

      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.MODULE_VERSION }}
          fetch-depth: 2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set Build Modules
        run: |
          echo ::set-env name=MODIFY_FILES::$(git diff --name-only HEAD~2 HEAD)
          echo MODIFY_FILES: ${MODIFY_FILES}
          MODULES=""
          if [[ $MODIFY_FILES =~ "[^/] \{,1\}pom.xml$" ]]; then
             MODULES=${MODULES}",com.github.fosin.anan:anan-cloud"
          fi
          if [[ $MODIFY_FILES =~ "anan-cloudadviced/pom.xml" ]]; then
            MODULES=${MODULES}",com.github.fosin.anan:anan-cloudadviced"
          fi
          if [[ $MODIFY_FILES =~ "anan-cloudadviced/anan-platform/pom.xml" ]]; then
            MODULES=${MODULES}",com.github.fosin.anan:anan-platform"
          fi
          if [[ $MODIFY_FILES =~ "anan-platformapi" ]]; then
            MODULES=${MODULES}",com.github.fosin.anan:anan-platformapi"
          fi
          if [[ $MODIFY_FILES =~ "anan-platformpojo" ]]; then
            MODULES=${MODULES}",com.github.fosin.anan:anan-platformpojo"
          fi
          echo ::set-env name=MODULE_LIST::${MODULES:1}
          echo MODULE_LIST: ${{ env.MODULE_LIST }}
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        if: env.MODULE_LIST != ''
        with:
          #gpg_private_key: ${{ secrets.gpg_private_key }}
          #gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.center_nexus_username }}
          nexus_password: ${{ secrets.center_nexus_password }}
          #directory: "."
          maven_profiles: "sonatype-oss-release"
          maven_goals_phases: "clean package deploy:deploy"
          maven_args: "-Dmaven.javadoc.skip=true -pl ${{ env.MODULE_LIST }}"
          server_id: "sonatype-nexus-snapshots"
      - name: Docker Hub Login
        if: contains(env.MODIFY_FILES,'deploy/openjdk') || contains(env.MODIFY_FILES,'deploy/mysql')
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
      # 创建adoptopenjdk11-openj9镜像
      - name: Docker build and push adoptopenjdk-11-jdk-openj9
        if: contains(env.MODIFY_FILES,'deploy/openjdk/11-openj9.Dockerfile') || contains(env.MODIFY_FILES,'.sh') || contains(env.MODIFY_FILES,'sources.list')
        env:
          MODULE_NAME: adoptopenjdk
          MODULE_VERSION: 11-jdk-openj9
          MODULE_PATH: deploy/openjdk
        run: |
          docker build $MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f $MODULE_PATH/11-openj9.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
      # 创建jdk11镜像
      - name: Docker build and push openjdk11
        if: contains(env.MODIFY_FILES,'deploy/openjdk/11.Dockerfile') || contains(env.MODIFY_FILES,'.sh') || contains(env.MODIFY_FILES,'sources.list')
        env:
          MODULE_NAME: adoptopenjdk
          MODULE_VERSION: 11-jdk-hotspot
          MODULE_PATH: deploy/openjdk
        run: |
          docker build $MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f $MODULE_PATH/11.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
      # 创建jdk8镜像
      - name: Docker build and push openjdk8
        if: contains(env.MODIFY_FILES,'deploy/openjdk/8.Dockerfile') || contains(env.MODIFY_FILES,'.sh') || contains(env.MODIFY_FILES,'sources.list')
        env:
          MODULE_NAME: adoptopenjdk
          MODULE_VERSION: 8-jdk-hotspot
          MODULE_PATH: deploy/openjdk
        run: |
          docker build $MODULE_PATH -t fosin/$MODULE_NAME:MODULE_VERSION -f $MODULE_PATH/8.Dockerfile
          docker push fosin/$MODULE_NAME:MODULE_VERSION
      - name: Docker build and push mysql-master
        if: contains(env.MODIFY_FILES,'deploy/mysql/master')
        env:
          MODULE_NAME: mysql-master
          MODULE_VERSION: 2.1.0
          MODULE_PATH: deploy/mysql/master
        run: |
          docker build ./$MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f ./$MODULE_PATH/7.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
      - name: Docker build and push mysql-slave
        if: contains(env.MODIFY_FILES,'deploy/mysql/slave')
        env:
          MODULE_NAME: mysql-slave
          MODULE_VERSION: 2.1.0
          MODULE_PATH: deploy/mysql/slave
        run: |
          docker build ./$MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f ./$MODULE_PATH/7.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
