name: Zuulgateway Master Dockerfile CI
env:
  MODULE_NAME: anan-zuulgateway
  MODULE_VERSION: 2.1.0-SNAPSHOT
  MODULE_PROFILE: local
  MODULE_PATH: anan-cloudadviced/anan-zuulgateway
on:
  push:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
  pull_request:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branche
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.6'
          architecture: x64
      - name: Build with Maven
        run: |
          mvn --batch-mode --errors --file $MODULE_PATH/pom.xml clean compile jar:jar spring-boot:repackage
      - name: Docker build and push image
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
          docker build ./$MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f ./$MODULE_PATH/Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
