# This is a basic workflow to help you get started with Actions

name: Master Dockerfile CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
    - 'deploy/openjdk/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'deploy/openjdk/**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master

    # 创建jdk11镜像
    - name: 11-jdk
      run: |
        docker login --username=${{ secrets.aliyun_user }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.aliyun_pass }}
        docker build -t registry.cn-hangzhou.aliyuncs.com/fosin/openjdk:11-jdk -f deploy/openjdk/Dockerfile deploy/openjdk 
        docker push registry.cn-hangzhou.aliyuncs.com/fosin/openjdk:11-jdk

