name: OpenJDK11 Master Dockerfile CI
env:
  MODULE_NAME: openjdk
  MODULE_VERSION: 11-jdk
  MODULE_PATH: deploy/openjdk
on:
  push:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
  pull_request:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 创建jdk11镜像
      - name: Docker build and push image
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
          docker build ./$MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f ./$MODULE_PATH/11.github.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
