name: Mysql5.7 Slave Dockerfile CI
env:
  MODULE_NAME: mysql-slave
  MODULE_VERSION: 5.7
  MODULE_PATH: deploy/mysql/slave
on:
  push:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
  pull_request:
    branches: [ master ]
    paths:
      - '$MODULE_PATH/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 创建镜像并推送
      - name: Docker build and push image
        run: |
          docker login --username=${{ secrets.dockerhub_user }} --password=${{ secrets.dockerhub_pass }}
          docker build ./$MODULE_PATH -t fosin/$MODULE_NAME:$MODULE_VERSION -f ./$MODULE_PATH/7.Dockerfile
          docker push fosin/$MODULE_NAME:$MODULE_VERSION
