spring:
  jpa:
    show-sql: true
  datasource:
    druid:
      his:
        url: jdbc:oracle:thin:@10.211.10.35:1521:yaoan
        username: '{cipher}AQBHrAB9SJPoyY/R6JcfO1/cQ5BvZi0vw3YTRPPvkNr2YHb27I7/IYM/lZoytHdT5btPz8Jy+7cQLARHl1wVLkD0rAt+pDM486vRX8RN3pFDRbdAkAK7RsdGw55C3Gh2TdS06Bp6y8OgQa0+KHEroN59DzGCv70JM0m4z91Up5pOEWBVFNBTBD+8l/IduPpcIms9ZXEs0xfR8EHfcsUvEYlcUSHO1/6rHU3dIHjw9uVTttB6Ut9m2JZXi7IqKIP08ZU7u33ex6bG5Rfhv1fh3fQaLUWvfSSGhj1ptuvP6kDeV5SMb2JqM/+81E+jr2sjFNX4nB4Mh/iFlBVyBerHMb9cS1NCisj27+AVdiEG72c79jxUBcl3L1LQYUFehH0shcE='
        password: '{cipher}AQBHrAB9SJPoyY/R6JcfO1/cQ5BvZi0vw3YTRPPvkNr2YHb27I7/IYM/lZoytHdT5btPz8Jy+7cQLARHl1wVLkD0rAt+pDM486vRX8RN3pFDRbdAkAK7RsdGw55C3Gh2TdS06Bp6y8OgQa0+KHEroN59DzGCv70JM0m4z91Up5pOEWBVFNBTBD+8l/IduPpcIms9ZXEs0xfR8EHfcsUvEYlcUSHO1/6rHU3dIHjw9uVTttB6Ut9m2JZXi7IqKIP08ZU7u33ex6bG5Rfhv1fh3fQaLUWvfSSGhj1ptuvP6kDeV5SMb2JqM/+81E+jr2sjFNX4nB4Mh/iFlBVyBerHMb9cS1NCisj27+AVdiEG72c79jxUBcl3L1LQYUFehH0shcE='
        initial-size: 5 #初始化大小
        min-idle: 5 #最小
        maxActive: 30 # 最大
        maxWait: 60000 #配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
    #      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    #      maxPoolPreparedStatementPerConnectionSize: 20
    #      filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #      useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    #    platform: mysql
    #    continue-on-error: true
      lis:
        url: jdbc:sqlserver://192.168.2.250\MSSQL2016:49918;database=xflis
        username: sa
        password: '{cipher}AQAB30DlnFWqNZlTKUPW9tiqS3b/p3AUJ9q7zatMfysgDbRmB47rKHQZi+JUl4iP0JeNVweldrbDQa/Ga+zMP/ubyqoxZqmvH7rvzHllBLqCrAQDUSp8SGB/hyNN4gy2cFNTDzyHXBljj1He2NWi/Rm6Yyobo1hWOL9MeUqKijPQrnbF2vm4cjDeJRx22sK7im3ljus10R/1NXycBYLEgKs0l8oeCFMxixGCNIw/mf3JBJ94JsQz+pppKQm+1jxBVPLI4fESIZmB0pboXRqVBP6ZSJPed80JU+B9ePVVLetGnuPAV6Ous6CuAVBLn9VDOuKVF4x7NMLUECJUdNscKLjosGI8LaJzZWxQeaSXenq7TfVOkARJG9GkqskHkVlmyGE='
      tj:
        url: jdbc:oracle:thin:@10.211.10.35:1521:orcl
        #        url: jdbc:sqlserver://localhost:1433;DatabaseName=test1;
        username: '{cipher}AQBHrAB9SJPoyY/R6JcfO1/cQ5BvZi0vw3YTRPPvkNr2YHb27I7/IYM/lZoytHdT5btPz8Jy+7cQLARHl1wVLkD0rAt+pDM486vRX8RN3pFDRbdAkAK7RsdGw55C3Gh2TdS06Bp6y8OgQa0+KHEroN59DzGCv70JM0m4z91Up5pOEWBVFNBTBD+8l/IduPpcIms9ZXEs0xfR8EHfcsUvEYlcUSHO1/6rHU3dIHjw9uVTttB6Ut9m2JZXi7IqKIP08ZU7u33ex6bG5Rfhv1fh3fQaLUWvfSSGhj1ptuvP6kDeV5SMb2JqM/+81E+jr2sjFNX4nB4Mh/iFlBVyBerHMb9cS1NCisj27+AVdiEG72c79jxUBcl3L1LQYUFehH0shcE='
        password: '{cipher}AQBHrAB9SJPoyY/R6JcfO1/cQ5BvZi0vw3YTRPPvkNr2YHb27I7/IYM/lZoytHdT5btPz8Jy+7cQLARHl1wVLkD0rAt+pDM486vRX8RN3pFDRbdAkAK7RsdGw55C3Gh2TdS06Bp6y8OgQa0+KHEroN59DzGCv70JM0m4z91Up5pOEWBVFNBTBD+8l/IduPpcIms9ZXEs0xfR8EHfcsUvEYlcUSHO1/6rHU3dIHjw9uVTttB6Ut9m2JZXi7IqKIP08ZU7u33ex6bG5Rfhv1fh3fQaLUWvfSSGhj1ptuvP6kDeV5SMb2JqM/+81E+jr2sjFNX4nB4Mh/iFlBVyBerHMb9cS1NCisj27+AVdiEG72c79jxUBcl3L1LQYUFehH0shcE='
  redis:
    database: 10
    host: 192.168.2.242
    port: 6379
    password: '{cipher}AQBDc1ErZqS+aPq0dXnNf3P7r80dn83dGdU7YPhuD3LzVKWdpdA7IMq+l3pScI+NnZnBEy1T8rFtFGl51q200vAyTaWI6XrsCp5J/wtiY3pHaQk98b1NHVRFWRshXYSSLVIuaDBFAt6dFedbBTfh53U8bHEiHxaw85dSwWbRO/oCY7/ct1MmrS6zIVgIrBokou/6HACoczLtwSIjj8F/R/Divrc7Po9TpZBJvsxVrrzW82yqeRejci1jB06Si53n+/XgnIyNvpZFMYPTQwexp5Xc31kQwDuUYmftnIvrGv+XIEezNtgtIJWe1TzedGnytTCYu8bz3FSRsHvRievafRntlgqGxKonxBAtzOWza3V74QUq4E+fdOi2T3Go4kD2/PY='
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
info: #定义各种额外的详情给服务端显示
  description: "@project.description@"
  version: "@project.version@"
jasypt:
  encryptor:
    password: 56uyn56un67u57i
cdp:
  swagger:
    enabled: true
    title: ${spring.application.name}
    description: ${info.description}
    version: ${info.version}
    base-package: com.xingyj.op
    authorization:
      name: Oauth2.0 Authorization
      keyName: Authorization
    #      authRegex: ^[^/oauth/token]$
    contact:
      name: fosin
      email: 28860823@qq.com
  oauth2:
    disablecsrf: true
    disableHttpBasic: true
    blackWhiteList:
      - path: /**/v2/api-docs
